version: "3.8"

services:

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: you_can_tell_me_bot-php
    ports:
      - "443"
      - "80"
    working_dir: /var/www/
    volumes:
      - ./:/var/www/
#   command: bash -c "php composer.phar install && php index.php you-can-tell-me-bot:test"