version: "3.8"

services:

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: you_can_tell_me_bot-php
    ports:
      - "443"
      - "80"
    working_dir: /var/www/
    volumes:
      - ./:/var/www/
    environment:
      API_ID: ${API_ID}
      API_HASH: ${API_HASH}
      PHONE_NUMBER: ${PHONE_NUMBER}
      FIRST_NAME: ${FIRST_NAME}
      LAST_NAME: ${LAST_NAME}